Change feeds to use local datetime
porglezomp-misc/feedburst pull request #69
Opened 2018-10-03 18:37 UTC by zxey

Internally the Feed struct uses Utc datetimes converted from local datetimes.
Datetime stored in feed files are always stored as local.

The basic process is:
- Feed is read from feed file with local datetime (FeedEvent::read).
- This is then converted to Feed struct which internally stores datetime as Utc
- When we want to know if feed is scheduled, we find the duration from Utc datetime to Local datetime (this is handled by chrono).

I must say the test_parse_events test, gave me pretty hard time to fix, I could not find simple way to get the offset from Utc datetime to Local datetime in chrono crate, but it works now.

Fixes #58

2018-10-03 19:12 UTC, porglezomp commented
I'm not super experienced with date handling code, so I don't have a super strong opinion on it, but can you explain the decision to store time as local times and do math with UTC?

Also, will this tolerate the switch-over? I suspect the `parse()` call on the `DateTime<Local>` will handle it, but that's also worth double-checking.

2018-10-03 20:53 UTC, zxey commented
Now that I think of it, it is much easier to parse datetime as Utc, as it was before, and when we check if comic is scheduled, we just convert this Utc datetime to our local time and check elapsed time against that.

It is much better solution, I don't know why I didn't think of that earlier.

Changed the commit to reflect latest changes.

2018-10-03 21:23 UTC, porglezomp requested changes
Wow, this became much simpler.

I think there are a few more changes in `is_scheduled` that need to be made in order to avoid some edge cases that weren't properly handled previously though, and it'd be good to fix those here.

2018-10-03 21:23 UTC, porglezomp commented on src/feed.rs
> +        let last_read = self.last_read.with_timezone(&Local);
Need to update all uses in the function to refer to this `last_read`.

2018-10-03 21:23 UTC, porglezomp commented on src/feed.rs
> +        let elapsed_time = Local::now().signed_duration_since(last_read);
The `On` case probably needs to loop from the `last_read`'s day all the way to the `now` day, rather than using `elapsed_time.num_days()`, to account for incomplete days.

2018-10-03 21:28 UTC, porglezomp commented
Exploring the semantics of the `is_scheduled` policies:

`@ every # day(s)` should wait at least # days. I *think* this should be independent of the times during those days, so if you read it at midnight on one day, and the morning a week later, less than 7 days have elapsed, but it should be considered as 7 days. I think this one is handled incorrectly, and we need to count days of the week rather than number of days in the elapsed time.

`@ on monday/tuesday/etc` should require that it was last read before that day, and it is now that day or later. Currently, if you last read it sunday night, and it's marked as `@ on monday`, I believe it will currently think 0 days have passed, and so not realize that you went from sunday -> monday.

If you could add test cases for these two edge cases, that would also be very much appreciated.

2018-10-03 21:49 UTC, zxey commented on src/feed.rs
> +        let last_read = self.last_read.with_timezone(&Local);
Fixed

2018-10-03 22:01 UTC, porglezomp commented
Since it makes it easier to test, I'd also approve of changing `is_scheduled` to accept the "current" time as a parameter.

2018-10-04 17:59 UTC, zxey commented
Ok, I changed the is_scheduled to accept datetime, I also changed how is determined if the feed has already been read at least one. Before you would store MIN_DATE if you did not read it at least once, now it is Option with Some(DateTime) or None if the feed has not been read.

2018-10-04 19:13 UTC, porglezomp commented
Do you want to handle those other edge condition issues I brought up, or do you want me to make that a separate issue? This is a good improvement already, so it's up to you.

2018-10-05 11:14 UTC, zxey commented
Yeah, maybe it'll be better to open separate issue. We can then discuss how to handle these two edge cases properly.

2018-10-05 16:46 UTC, porglezomp commented
Okay, in that case, you need to re-run rustfmt on this so Travis will accept it.

2018-10-05 16:48 UTC, porglezomp approved these changes
LGTM

2018-10-07 07:09 UTC, merged

2018-10-07 07:09 UTC, porglezomp commented
Merged, thanks for your fix!